### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Anastasiya6** [Anastasiya6/homepage#8]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Nikita02091985** [comment]
- https://twitter.com/Ryu

- https://www.instagram.com/Ryu\

- Ryuhitting@gmail.com
